// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTn-HbKo_MkSEgSH04fe3rEXSMYZSBDyg',
    appId: '1:539730271126:web:8878c642251ab28feddbb7',
    messagingSenderId: '539730271126',
    projectId: 'shrawaka-236a4',
    authDomain: 'shrawaka-236a4.firebaseapp.com',
    storageBucket: 'shrawaka-236a4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_tidi3jXv1tZkdJmPNbyesk4aHbKl65o',
    appId: '1:539730271126:android:da4ce2c53b4c7313eddbb7',
    messagingSenderId: '539730271126',
    projectId: 'shrawaka-236a4',
    storageBucket: 'shrawaka-236a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALYwiXx5KSS7xKZmbXMoEHN-EZPBttibU',
    appId: '1:539730271126:ios:fb6a460fb6ae2dd6eddbb7',
    messagingSenderId: '539730271126',
    projectId: 'shrawaka-236a4',
    storageBucket: 'shrawaka-236a4.firebasestorage.app',
    iosBundleId: 'com.example.shrawaka',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALYwiXx5KSS7xKZmbXMoEHN-EZPBttibU',
    appId: '1:539730271126:ios:fb6a460fb6ae2dd6eddbb7',
    messagingSenderId: '539730271126',
    projectId: 'shrawaka-236a4',
    storageBucket: 'shrawaka-236a4.firebasestorage.app',
    iosBundleId: 'com.example.shrawaka',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTn-HbKo_MkSEgSH04fe3rEXSMYZSBDyg',
    appId: '1:539730271126:web:f72f1a27328b8b89eddbb7',
    messagingSenderId: '539730271126',
    projectId: 'shrawaka-236a4',
    authDomain: 'shrawaka-236a4.firebaseapp.com',
    storageBucket: 'shrawaka-236a4.firebasestorage.app',
  );
}
